apps/vehiculos/urls.py
from django.urls import path
from apps.vehiculos.views import *

app_name = 'vehiculos'
urlpatterns = [
    path('', listVehiculos, name='listVehiculos'),
    path('nuevo/', vehiculoCreate, name='vehiculoCreate'),
    path('actualizar/<int:id_vehiculos>/', vehiculoEdit, name='vehiculoEdit'),
    path('eliminar/<int:id_vehiculos>/', vehiculoEliminar, name='vehiculoEliminar'),


    path('marca/', listMarcas, name='listMarcas'),
    path('nuevo_m/', marcaCreate, name='marcaCreate'), 
    path('actualizar_m/<int:id_marca>/', marcaEdit, name='marcaEdit'), 
    path('eliminar_m/<int:id_marca>/', marcaEliminar, name='marcaEliminar'), 

    
    path('tipoVehiculos/', listTipoVehiculo, name='listTipoVehiculo'),
    path('nuevo_t/', tipoVehiculosCreate, name='tipoVehiculosCreate'), 
    path('actualizar_t/<int:id_tipoVehiculo>/', tipoVehiculosEdit, name='tipoVehiculosEdit'), 
    path('eliminar_t/<int:id_tipoVehiculo>/', tipoVehiculosEliminar, name='tipoVehiculosEliminar'), 
]

cmgvehiculos/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.vehiculos.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('vehiculos/', include('apps.vehiculos.urls', namespace='vehiculos')),
    path('ventas/', include('apps.ventas.urls', namespace='ventas')),
]

templates/tipoVehiculos/listTipoVehiculos.html
{% extends 'base/base.html' %}

{% block content %}

<h1 class="pull-right">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-3">
            <h3> Listado Tipo de Vehiculos</h3>
        </div>
        <div class="col-3"></div>
        <div class="col-3">
            <a href="{% url 'vehiculos:tipoVehiculosCreate' %}" class="btn btn-danger"> Adicionar <i class="fa-solid fa-circle-plus"></i></a>
        </div>
    </div>
</h1>

<table class="table table-secondary table-hover">
    <thead>
      <tr class="table-success" >
        <th scope="col">Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
     {% if vehiculos %}
        {% for tipoVehiculo in vehiculos %}
            <tr>
                <td>{{ tipoVehiculo.id}}</td>
                <td>{{ tipoVehiculo.nombre}}</td>
                <td>
                <a href="{% url 'vehiculos:tipoVehiculosEdit' tipoVehiculo.id %}" class="btn btn-success btn-xs">
                    <i class="fa-solid fa-pen"></i>
                </a>
                <a href="{% url 'vehiculos:tipoVehiculosEliminar' tipoVehiculo.id %}" class="btn btn-danger btn-xs">
                    <i class="fa-solid fa-trash-can"></i>
                </a>
                </td>
            </tr>
        {% endfor %}
      {% else %}
            <h3> ¡Lista Vacía!: No existen registros</h3>
        {%endif%}
    
    </tbody>
  </table>
{% endblock %}

templates/tipoVehiculos/tipoVehiculosEliminar.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <h4> ¿Desea eliminar el registro de {{tipoVehiculos.nombre}}?</h4>
    <button class="btn btn-danger" type="submit"> Si, eliminar</button>
    <a href="{% url 'vehiculos:listTipoVehiculo' %}" class="btn btn-primary">Cancelar</a>
</form>

{% endblock %}

templates/tipoVehiculos/tipoVehiculos_form.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
       <div class="row" style="padding: 20px">
           <div class="col-3"></div>
           <div class="col-4" style=" background-color:rgb(57, 205, 200);padding: 5px">
                <div align ="center" class="form-secondary">
                    <label for=""> {{ form.as_p }}</label>
                </div>
                <div align ="center" class="form-group">
                    <button class="btn btn-success" type="submit">
                        Guardar Datos
                    </button>
                </div>
            </div>
       </div>

      
    </form>
{% endblock  %}