apps/vehiculos/urls.py
from django.urls import path
from apps.vehiculos.views import *

app_name = 'vehiculos'
urlpatterns = [
    path('', listVehiculos, name='listVehiculos'),
    path('nuevo/', vehiculoCreate, name='vehiculoCreate'),
    path('actualizar/<int:id_vehiculos>/', vehiculoEdit, name='vehiculoEdit'),
    path('eliminar/<int:id_vehiculos>/', vehiculoEliminar, name='vehiculoEliminar'),


    path('marca/', listMarcas, name='listMarcas'),
    path('nuevo_m/', marcaCreate, name='marcaCreate'), 
    path('actualizar_m/<int:id_marca>/', marcaEdit, name='marcaEdit'), 
    path('eliminar_m/<int:id_marca>/', marcaEliminar, name='marcaEliminar'), 

    
    path('tipoVehiculos/', listTipoVehiculo, name='listTipoVehiculo'),
    path('nuevo_t/', tipoVehiculosCreate, name='tipoVehiculosCreate'), 
    path('actualizar_t/<int:id_tipoVehiculo>/', tipoVehiculosEdit, name='tipoVehiculosEdit'), 
    path('eliminar_t/<int:id_tipoVehiculo>/', tipoVehiculosEliminar, name='tipoVehiculosEliminar'), 
]

apps/ventas/urls.py
from django.urls import path
from apps.ventas.views import *

app_name='ventas'
urlpatterns = [
    path('', listVentas, name='listVentas'),
    path('nuevo/', ventaCreate, name='ventaCreate'),
    path('actualizar/<int:id_venta>/', ventaEdit, name='ventaEdit'), 
    path('eliminar/<int:id_venta>/', ventaElim, name='ventaElim'), 


    path('VehiculoVenta/', listVehiculoVentas, name='listVehiculoVentas'),
    path('nuevo_vv/', vehiculoVentasCreate, name='vehiculoVentasCreate'), 
    path('actualizar_vv/<int:id_vehiculoVenta>/', vehiculoVentasEdit, name='vehiculoVentasEdit'), 
    path('eliminar_vv/<int:id_vehiculoVenta>/', vehiculoVentasEliminar, name='vehiculoVentasEliminar'), 


    path('Usuarios/', listUsuarios, name='listUsuarios'),
    path('nuevo_u/', usuariosCreate, name='usuariosCreate'), 
    path('actualizar_u/<int:id_usuario>/', usuariosEdit, name='usuariosEdit'), 
    path('eliminar_u/<int:id_usuario>/', usuariosEliminar, name='usuariosEliminar'),


    path('consulta1/', consulta1, name='consulta1'),
    path('consulta2/', consulta2, name='consulta2'),
    path('consulta3/', consulta3, name='consulta3'),
    path('consulta4/', consulta4, name='consulta4'),
]

cmgvehiculos/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.vehiculos.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('vehiculos/', include('apps.vehiculos.urls', namespace='vehiculos')),
    path('ventas/', include('apps.ventas.urls', namespace='ventas')),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">INICIO
                  <span class="visually-hidden">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'vehiculos:listVehiculos' %}">VEHICULOS</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'ventas:listVentas' %}">VENTAS</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'vehiculos:listMarcas' %}">MARCA</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'vehiculos:listTipoVehiculo' %}">TIPO DE VEHICULO</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'ventas:listVehiculoVentas' %}">VEHICULO VENTA</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'ventas:listUsuarios' %}">USUARIOS</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link active dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">CONSULTAS</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'ventas:consulta1' %}">Consulta 1</a>
                  <a class="dropdown-item" href="{% url 'ventas:consulta2' %}">Consulta 2</a>
                  <a class="dropdown-item" href="{% url 'ventas:consulta3' %}">Consulta 3</a>
                  <a class="dropdown-item" href="{% url 'ventas:consulta4' %}">Consulta 4</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    {% block content %}


    {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>