apps/ventas/urls.py
from django.urls import path
from apps.ventas.views import *

app_name='ventas'
urlpatterns = [
    path('', listVentas, name='listVentas'),
    path('nuevo/', ventaCreate, name='ventaCreate'),
    path('actualizar/<int:id_venta>/', ventaEdit, name='ventaEdit'), 
    path('eliminar/<int:id_venta>/', ventaElim, name='ventaElim'), 


    path('VehiculoVenta/', listVehiculoVentas, name='listVehiculoVentas'),
    path('nuevo_vv/', vehiculoVentasCreate, name='vehiculoVentasCreate'), 
    path('actualizar_vv/<int:id_vehiculoVenta>/', vehiculoVentasEdit, name='vehiculoVentasEdit'), 
    path('eliminar_vv/<int:id_vehiculoVenta>/', vehiculoVentasEliminar, name='vehiculoVentasEliminar'), 


    path('Usuarios/', listUsuarios, name='listUsuarios'),
    path('nuevo_u/', usuariosCreate, name='usuariosCreate'), 
    path('actualizar_u/<int:id_usuario>/', usuariosEdit, name='usuariosEdit'), 
    path('eliminar_u/<int:id_usuario>/', usuariosEliminar, name='usuariosEliminar'),


    path('consulta1/', consulta1, name='consulta1'),
    path('consulta2/', consulta2, name='consulta2'),
    path('consulta3/', consulta3, name='consulta3'),
    path('consulta4/', consulta4, name='consulta4'),
]

cmgvehiculos/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.vehiculos.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('vehiculos/', include('apps.vehiculos.urls', namespace='vehiculos')),
    path('ventas/', include('apps.ventas.urls', namespace='ventas')),
]

templates/usuarios/listUsuarios.html
{% extends 'base/base.html' %}

{% block content %}

<h1 class="pull-right">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-3">
            <h3> Listado de Usuarios</h3>
        </div>
        <div class="col-3"></div>
        <div class="col-3">
            <a href="{% url 'ventas:usuariosCreate' %}" class="btn btn-danger"> Adicionar <i class="fa-solid fa-circle-plus"></i></a>
        </div>
    </div>
</h1>

<table class="table table-secondary table-hover">
    <thead>
      <tr class="table-success" >
        <th scope="col">Id</th>
        <th scope="col">Nombre Completo</th>
        <th scope="col">Tipo de Identificación</th>
        <th scope="col">Número de Identificación</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Dirección</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
     {% if venta %}
        {% for usuario in ventas %}
            <tr>
                <td>{{ usuario.id}}</td>
                <td>{{ usuario.nombres}}</td>
                <td>{{ usuario.tipoIdentificacion}}</td>
                <td>{{ usuario.num_identificacion}}</td>
                <td>{{ usuario.telefono}}</td>
                <td>{{ usuario.direccion}}</td>
                <td>
                <a href="{% url 'ventas:usuariosEdit' usuario.id %}" class="btn btn-success btn-xs">
                    <i class="fa-solid fa-pen"></i>
                </a>
                <a href="{% url 'ventas:usuariosEliminar' usuario.id %}" class="btn btn-danger btn-xs">
                    <i class="fa-solid fa-trash-can"></i>
                </a>
                </td>
            </tr>
        {% endfor %}
      {% else %}
            <h3> ¡Lista Vacía!: No existen registros</h3>
        {%endif%}
    
    </tbody>
  </table>
{% endblock %}

templates/usuarios/usuarioEliminar.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <h4> ¿Desea eliminar el registro de {{usuarios.nombres}}?</h4>
    <button class="btn btn-danger" type="submit"> Si, eliminar</button>
    <a href="{% url 'ventas:listUsuarios' %}" class="btn btn-primary">Cancelar</a>
</form>

{% endblock %}

templates/usuarios/usuario_form.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
       <div class="row" style="padding: 20px">
           <div class="col-3"></div>
           <div class="col-4" style=" background-color:rgb(66, 225, 227);padding: 5px">
                <div align ="center" class="form-group">
                    <label for=""> {{ form.as_p }}</label>
                </div>
                <div align ="center" class="form-group">
                    <button class="btn btn-primary" type="submit">
                        Guardar Datos
                    </button>
                </div>
            </div>
       </div>

      
    </form>
{% endblock  %}